# Generated by Django 2.2 on 2019-04-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortflix', '0006_movie_movie_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_length',
            field=models.TimeField(default='1:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='skip_intro',
            field=models.TimeField(default='0:02'),
            preserve_default=False,
        ),
    ]
